baseURL = 'https://nitonabbc.org/'
languageCode = 'ja'
title = '仁戸名聖書バプテスト教会'

[params]
description = "仁戸名聖書バプテスト教会は、1963年に創設以来、60年以上にわたり地域の方々にキリストの愛をお伝えしてきた教会です。"
imgDir = "https://nitonabbc.org/img/"

[markup]
  [markup.goldmark]
    [markup.goldmark.parser]
      [markup.goldmark.parser.attribute]
        block = true
